version: '3.8'
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: paper
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 5G
      CONSOLE: "false"
    ports:
      - 25565:25565
      - 24454:24454/udp
    volumes:
      - /etc/docker/container/mc-paper:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false" 
volumes:
  mc-paper: